# Generated by Django 4.2.25 on 2025-10-15 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='season',
            field=models.CharField(choices=[('summer', 'Лето'), ('autumn', 'Осень'), ('winter', 'Зима'), ('spring', 'Весна')], default='summer', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('shirt', 'Футболка'), ('jacket', 'Куртка'), ('pants', 'Брюки'), ('shoes', 'Обувь'), ('accessory', 'Аксессуар')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='items',
            field=models.ManyToManyField(related_name='outfits', to='wardrobe.item'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL),
        ),
    ]
