# Generated by Django 4.2.25 on 2025-10-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_rename_owner_item_user_item_color_item_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visibility',
            field=models.CharField(choices=[('private', 'Только я'), ('public', 'Видно всем')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='outfit',
            name='visibility',
            field=models.CharField(choices=[('private', 'Только я'), ('public', 'Видно всем')], default='private', max_length=10),
        ),
    ]
