services:
  - type: web
    name: digital_wardrobe
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      gunicorn digital_wardrobe.wsgi:application
