services:
  - type: web
    name: digital_wardrobe
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    preDeployCommand: |
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput
      gunicorn digital_wardrobe.wsgi:application

