services:
  - type: web
    name: digital_wardrobe
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py shell -c "from django.contrib.auth import get_user_model; User=get_user_model(); import os,sys; u=os.getenv('ADMIN_USER','admin'); e=os.getenv('ADMIN_EMAIL','admin@example.com'); p=os.getenv('ADMIN_PASSWORD','admin1234'); (User.objects.filter(username=u).exists() or User.objects.create_superuser(u,e,p)) and sys.stdout.write('✅ Admin created or exists\n')"
      gunicorn digital_wardrobe.wsgi:application
